<template>
  <div class="sample-build-progress">
    <div class="header">
      <h2>{{ $t('build.title') }}</h2>
      <div class="controls">
        <button 
          @click="startBuild" 
          :disabled="isBuilding"
          class="btn btn-primary"
        >
          {{ isBuilding ? $t('build.button.building') : $t('build.button.start') }}
        </button>
        <button 
          @click="cancelBuild" 
          :disabled="!isBuilding"
          class="btn btn-danger"
        >
          {{ $t('build.button.cancel') }}
        </button>
        <button 
          @click="startOver" 
          class="btn btn-secondary"
        >
          {{ $t('build.button.startOver') }}
        </button>
      </div>
    </div>

    <div class="progress-section">
      <div class="progress-info">
        <div class="status">
          <span class="status-label">{{ $t('build.status.label') }}</span>
          <span :class="['status-value', statusClass]">{{ currentStatus }}</span>
        </div>
        <div class="progress-bar-container">
          <div class="progress-bar">
            <div 
              class="progress-fill" 
              :style="{ width: progress + '%' }"
            ></div>
          </div>
          <span class="progress-text">{{ progress }}%</span>
        </div>
      </div>
    </div>

    <div class="log-section">
      <div class="log-header">
        <h3>{{ $t('build.log.title') }}</h3>
        <div class="log-controls">
          <button 
            @click="toggleAutoScroll" 
            :class="['btn btn-sm', autoScroll ? 'btn-active' : 'btn-secondary']"
          >
            {{ autoScroll ? $t('build.button.autoScrollOn') : $t('build.button.autoScrollOff') }}
          </button>
        </div>
      </div>
      <div 
        ref="logContainer" 
        class="log-container"
        @scroll="onScroll"
      >
        <div class="log-content">
          <div 
            v-for="(log, index) in logs" 
            :key="index" 
            :class="['log-line', getLogClass(log)]"
          >
            {{ log }}
          </div>
          <div v-if="isBuilding" class="log-loader">
            <div class="spinner"></div>
            <span>{{ $t('build.status.building') }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, reactive, computed, onMounted, onUnmounted, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { EventsOn, EventsOff } from '../../wailsjs/runtime'
import { ElMessageBox } from 'element-plus'
import { useRouter } from 'vue-router'

// Import the sample build functions (these would be generated by Wails)
import { BuildImage, CancelBuild } from '../../wailsjs/go/main/App'

export default {
  name: 'SampleBuildProgress',
  setup() {
    const { t } = useI18n()
    // Reactive data
    const isBuilding = ref(false)
    const buildStatus = ref(0) // 0: idle, 1: failed, 2: success, 3: processing
    const progress = ref(0)
    const currentStatus = ref(t('build.status.ready'))
    const logs = ref([])
    const autoScroll = ref(true)
    const logContainer = ref(null)
    const router = useRouter()


    // Event channels
    const BUILD_STREAM_CHANNEL = 'SAMPLE_BUILD_STREAM'
    const BUILD_LOG_STREAM_CHANNEL = 'SAMPLE_BUILD_LOG_STREAM'

    // Methods
    const startBuild = async () => {
      if (isBuilding.value) return

      try {
        isBuilding.value = true
        progress.value = 0
        currentStatus.value = t('build.status.starting')
        logs.value = []
        buildStatus.value = 0
        
        // Start the build process
        await BuildImage(
          BUILD_STREAM_CHANNEL,
          BUILD_LOG_STREAM_CHANNEL,
          'admin123', // Sample admin password
          'sample-token' // Sample Azure token
        )
      } catch (error) {
        console.error('Failed to start build:', error)
        ElMessageBox.alert(error.message || t('build.message.failure'), t('build.dialog.failure'), {
          confirmButtonText: t('build.dialog.ok'),
          type: 'error',
        })
        isBuilding.value = false
        buildStatus.value = 1
        currentStatus.value = t('build.status.error')
      }
    }

    const cancelBuild = async () => {
      if (!isBuilding.value) return

      try {
        await CancelBuild()
        isBuilding.value = false
        currentStatus.value = t('build.status.cancelled')
      } catch (error) {
        console.error('Failed to cancel build:', error)
        ElMessageBox.alert(error.message || t('build.message.cancelFailure'), t('build.dialog.failure'), {
          confirmButtonText: t('build.dialog.ok'),
          type: 'error',
        })
      }
    }

    const startOver = () => {
      router.push('/')
    }

    const toggleAutoScroll = () => {
      autoScroll.value = !autoScroll.value
    }

    const onScroll = () => {
      if (!logContainer.value) return
      
      const { scrollTop, scrollHeight, clientHeight } = logContainer.value
      const isAtBottom = scrollTop + clientHeight >= scrollHeight - 10
      autoScroll.value = isAtBottom
    }

    const addLog = (logMessage) => {
      logs.value.push(logMessage.trim())
      
      // Keep only last 1000 lines to prevent memory issues
      if (logs.value.length > 1000) {
        logs.value = logs.value.slice(-1000)
      }

      if (autoScroll.value) {
        nextTick(() => {
          if (logContainer.value) {
            logContainer.value.scrollTop = logContainer.value.scrollHeight
          }
        })
      }
    }

    const getLogClass = (log) => {
      if (log.includes('[ERROR]')) return 'log-error'
      if (log.includes('[SUCCESS]')) return 'log-success'
      if (log.includes('[INFO]')) return 'log-info'
      if (log.includes('[WARNING]')) return 'log-warning'
      return 'log-normal'
    }

    // Computed properties
    const statusClass = computed(() => {
      if (currentStatus.value.includes(t('build.status.completed'))) return 'status-success'
      if (currentStatus.value.includes(t('build.status.failed')) || currentStatus.value.includes(t('build.status.error'))) return 'status-error'
      if (currentStatus.value.includes(t('build.status.building')) || currentStatus.value.includes(t('build.status.starting'))) return 'status-building'
      if (currentStatus.value.includes(t('build.status.cancelled'))) return 'status-cancelled'
      return 'status-ready'
    })

    // Event listeners
    const handleBuildProgress = (data) => {
      try {
        const result = JSON.parse(data)
        progress.value = result.percent || 0
        console.log(result.status);
        currentStatus.value = result.status ? t(`build.status.${result.status.toLowerCase().replace(/ /g, '')}`) : t('build.status.building')
        
        if (result.status === 'Build Image Completed') {
          isBuilding.value = false
          if (buildStatus.value !== 2) {
            ElMessageBox.alert(t('build.message.success'), t('build.dialog.success'), {
              confirmButtonText: t('build.dialog.ok'),
              type: 'success',
            })
          }
          buildStatus.value = 2
        } else if (result.status === 'Build Image Failed') {
          isBuilding.value = false
          if (buildStatus.value !== 1) {
            ElMessageBox.alert(currentStatus.value, t('build.dialog.failure'), {
              confirmButtonText: t('build.dialog.ok'),
              type: 'error',
            });
          }
          buildStatus.value = 1
        } else {
          buildStatus.value = 3
        }
      } catch (error) {
        console.error('Failed to parse build progress:', error)
      }
    }

    const handleBuildLog = (data) => {
      addLog(data)
    }

    // Lifecycle
    onMounted(() => {
      // Subscribe to build progress events
      EventsOn(BUILD_STREAM_CHANNEL, handleBuildProgress)
      EventsOn(BUILD_LOG_STREAM_CHANNEL, handleBuildLog)
    })

    onUnmounted(() => {
      // Unsubscribe from events
      EventsOff(BUILD_STREAM_CHANNEL)
      EventsOff(BUILD_LOG_STREAM_CHANNEL)
    })

    return {
      // Data
      isBuilding,
      buildStatus,
      progress,
      currentStatus,
      logs,
      autoScroll,
      logContainer,
      t,
      
      // Methods
      startBuild,
      cancelBuild,
      startOver,
      toggleAutoScroll,
      onScroll,
      getLogClass,
      
      // Computed
      statusClass,
    }
  }
}
</script>

<style scoped>
.sample-build-progress {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 15px;
  border-bottom: 2px solid #e0e0e0;
}

.header h2 {
  margin: 0;
  color: #333;
  font-size: 24px;
}

.controls {
  display: flex;
  gap: 10px;
}

.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: all 0.2s ease;
}

.btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-primary {
  background-color: #007bff;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background-color: #0056b3;
}

.btn-danger {
  background-color: #dc3545;
  color: white;
}

.btn-danger:hover:not(:disabled) {
  background-color: #c82333;
}

.btn-secondary {
  background-color: #6c757d;
  color: white;
}

.btn-secondary:hover:not(:disabled) {
  background-color: #545b62;
}

.btn-sm {
  padding: 4px 8px;
  font-size: 12px;
}

.btn-active {
  background-color: #28a745;
}

.progress-section {
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 20px;
  margin-bottom: 20px;
}

.progress-info {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.status {
  display: flex;
  align-items: center;
  gap: 10px;
}

.status-label {
  font-weight: 600;
  color: #495057;
}

.status-value {
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 14px;
  font-weight: 500;
}

.status-ready {
  background-color: #e9ecef;
  color: #6c757d;
}

.status-building {
  background-color: #cce5ff;
  color: #0066cc;
}

.status-success {
  background-color: #d4edda;
  color: #155724;
}

.status-error {
  background-color: #f8d7da;
  color: #721c24;
}

.status-cancelled {
  background-color: #fff3cd;
  color: #856404;
}

.progress-bar-container {
  display: flex;
  align-items: center;
  gap: 15px;
}

.progress-bar {
  flex: 1;
  height: 20px;
  background-color: #e9ecef;
  border-radius: 10px;
  overflow: hidden;
  position: relative;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #007bff, #0056b3);
  border-radius: 10px;
  transition: width 0.3s ease;
  position: relative;
}

.progress-fill::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: linear-gradient(
    90deg,
    transparent,
    rgba(255, 255, 255, 0.3),
    transparent
  );
  animation: shimmer 2s infinite;
}

@keyframes shimmer {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(100%); }
}

.progress-text {
  font-weight: 600;
  color: #495057;
  min-width: 40px;
  text-align: right;
}

.log-section {
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  overflow: hidden;
}

.log-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 15px 20px;
  background-color: #e9ecef;
  border-bottom: 1px solid #dee2e6;
}

.log-header h3 {
  margin: 0;
  color: #495057;
  font-size: 18px;
}

.log-controls {
  display: flex;
  gap: 10px;
}

.log-container {
  height: 400px;
  overflow-y: auto;
  background-color: #1e1e1e;
  color: #d4d4d4;
  font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
  font-size: 13px;
  line-height: 1.4;
}

.log-content {
  padding: 15px;
}

.log-line {
  margin-bottom: 2px;
  word-wrap: break-word;
  white-space: pre-wrap;
}

.log-normal {
  color: #d4d4d4;
}

.log-info {
  color: #569cd6;
}

.log-warning {
  color: #ffc107;
}

.log-error {
  color: #f44747;
}

.log-success {
  color: #4ec9b0;
}

.log-loader {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-top: 10px;
  color: #569cd6;
}

.spinner {
  width: 16px;
  height: 16px;
  border: 2px solid #569cd6;
  border-top: 2px solid transparent;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.error-dialog {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.error-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  max-width: 400px;
  text-align: center;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
}

.error-content h3 {
  margin: 0 0 15px 0;
  color: #dc3545;
}

.error-content p {
  margin: 0 0 20px 0;
  color: #495057;
}

/* Scrollbar styling */
.log-container::-webkit-scrollbar {
  width: 8px;
}

.log-container::-webkit-scrollbar-track {
  background: #2d2d2d;
}

.log-container::-webkit-scrollbar-thumb {
  background: #555;
  border-radius: 4px;
}

.log-container::-webkit-scrollbar-thumb:hover {
  background: #777;
}

/* Responsive design */
@media (max-width: 768px) {
  .header {
    flex-direction: column;
    gap: 15px;
    align-items: stretch;
  }

  .controls {
    justify-content: center;
  }

  .progress-bar-container {
    flex-direction: column;
    gap: 10px;
  }

  .log-header {
    flex-direction: column;
    gap: 10px;
    align-items: stretch;
  }
}
</style>
