// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildImage'](arg1, arg2, arg3, arg4);
}

export function CancelBuild() {
  return window['go']['main']['App']['CancelBuild']();
}

export function GetSampleBuildLog() {
  return window['go']['main']['App']['GetSampleBuildLog']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
