// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function CancelBuild():Promise<boolean>;

export function GetSampleBuildLog():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;
